<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="allegro_hand_left">

<xacro:property name="DEG2RAD" value="0.01745329251" />

<!-- ======================== BASE PARAMS ========================= -->

<xacro:property name="base_link_z" value="0.095" />

<!-- ======================== FINGER PARAMS ======================== -->

<xacro:property name="links_x" value="0.0196" />
<xacro:property name="links_y" value="0.0275" />

<xacro:property name="link0_z" value="0.0164" />
<xacro:property name="link1_z" value="0.0540" />
<xacro:property name="link2_z" value="0.0384" />
<!-- full height from joint to tip. when used,
the radius of the finger tip sphere will be subtracted
and one fixed link will be added for the tip. -->
<xacro:property name="link3_z" value="0.0387" /> 
<xacro:property name="fingerTip_r" value="0.0150" />


<!-- ========================= THUMB PARAMS ========================= -->

<xacro:property name="link0_t_x" value="0.0358" />
<xacro:property name="link0_t_y" value="0.0340" />
<xacro:property name="link0_t_z" value="0.0455" />

<xacro:property name="link1_t_z" value="0.0177" />
<xacro:property name="link2_t_z" value="0.0514" />
<xacro:property name="link3_t_z" value="0.0543" />


<!-- ========================= LIMITS ========================= -->

<xacro:property name="joint_safety_margin" value="0.1" />
<xacro:property name="limit_0_up" value="0.57" />
<xacro:property name="limit_0_low" value="-0.57" />
<xacro:property name="limit_1_up" value="1.71" />
<xacro:property name="limit_1_low" value="-0.296" />
<xacro:property name="limit_2_up" value="1.809" />
<xacro:property name="limit_2_low" value="-0.274" />
<xacro:property name="limit_3_up" value="1.718" />
<xacro:property name="limit_3_low" value=" -0.327" />

<xacro:property name="limit_0_t_up" value="1.496" />
<xacro:property name="limit_0_t_low" value="0.363" />
<xacro:property name="limit_1_t_up" value="1.263" />
<xacro:property name="limit_1_t_low" value="-0.205" />
<xacro:property name="limit_2_t_up" value="1.744" />
<xacro:property name="limit_2_t_low" value="-0.289" />
<xacro:property name="limit_3_t_up" value="1.819" />
<xacro:property name="limit_3_t_low" value="-0.262" />

<!-- ============================================================================= -->
<!-- ============================================================================= -->
<!-- ============================================================================= -->


<!-- BASE -->
  <link name="base_link">
    <visual>
      <geometry>
      	<!--     drawing  estimate  estimate  -->
        <box size="0.0408 0.1130 ${base_link_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="-0.009300 0 -${base_link_z/2}"/>
      <material name="blue">
        <color rgba="0 0 .8 1"/>
      </material>
    </visual>
  </link>

<!-- ============================================================================= -->

<!-- FINGERS -->
<xacro:property name="offset_origin_x_const" value="0" />
<xacro:property name="offset_origin_y_const" value="0.044981" />
<xacro:property name="offset_origin_z_const" value="0.002298" />

<!--  LEFT HAND due to which finger is number 0 -->
<!-- ALSO POSITIVE DIRECTIONS MAY HAVE TO CHANGE -->
<xacro:finger 
	finger_num=			"0"
	offset_origin_x=	"${offset_origin_x_const}"	
	offset_origin_y=	"-${offset_origin_y_const}"
	offset_origin_z=	"-${offset_origin_z_const}"
	finger_angle_r=		"${5.0*DEG2RAD}"
/>

<xacro:finger
	finger_num=			"1" 
	offset_origin_x=	"${offset_origin_x_const}"	
	offset_origin_y=	"0" 
	offset_origin_z=	"0" 
	finger_angle_r=		"0.0"
/>

<xacro:finger 
	finger_num=			"2" 
	offset_origin_x=	"${offset_origin_x_const}"	
	offset_origin_y=	"${offset_origin_y_const}" 
	offset_origin_z=	"-${offset_origin_z_const}" 
	finger_angle_r=		"-${5.0*DEG2RAD}"
/>

<xacro:thumb_left 
	finger_num=			"3" 
	offset_origin_x=	"-0.0182"	
	offset_origin_y=	"-0.0168753" 
	offset_origin_z=	"-0.07308" 
	
	
	finger_angle_r=		"0"
	finger_angle_p=		"-${95*DEG2RAD}"	
	finger_angle_y=		"${90*DEG2RAD}"
/>

<!-- -${95*DEG2RAD}    ${180*DEG2RAD} -->
	
<!-- ============================================================================= -->

<!-- LEFT -->
<!-- THUMB -->
<!-- Write code for left and right with proper changes
	(using variables for like comps) and include as 2 macros
	include both and comment unused for right and left -->

<!-- END LEFT -->



<!-- ============================================================================= -->
<!-- ============================================================================= -->
<!-- ============================================================================= -->


<!-- THUMB MACRO -->
<xacro:macro name="thumb_left" params="finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y">

<!-- [LINK 0] [LINK 0] [LINK 0] [LINK 0]  [LINK 0] [LINK 0] [LINK 0] -->
  
	<link name="link_${finger_num*4+0}">	
    <visual>
      <geometry>
        <box size="${link0_t_x} ${link0_t_y} ${link0_t_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="${-0.0358/2+0.027} ${0.034/2-0.026} ${0.045/2-0.008}"/>
      <material name="black">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+0}" type="revolute">
    <axis xyz="1 0 0"/>
     <limit effort="0" velocity="0" lower="${limit_0_t_low-joint_safety_margin}" upper="${limit_0_t_up-joint_safety_margin}" />
    <parent link="base_link"/>
    <child link="link_${finger_num*4+0}"/>
    <origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}" xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
  </joint>
  
  
<!-- [LINK 1] [LINK 1] [LINK 1] [LINK 1]  [LINK 1] [LINK 1] [LINK 1] -->
  
	<link name="link_${finger_num*4+1}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link1_t_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link1_t_z/2}"/>
      <material name="blue">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+1}" type="revolute">
    <axis xyz="0 0 -1"/>
     <limit effort="0" velocity="0" lower="${limit_1_t_low+joint_safety_margin}" upper="${limit_1_t_up-joint_safety_margin}" />
    <parent link="link_${finger_num*4+0}"/>
    <child link="link_${finger_num*4+1}"/>
    <origin xyz="0 0 ${0.0552-0.0177}"/>
  </joint>  


<!-- [LINK 2] [LINK 2] [LINK 2] [LINK 2]  [LINK 2] [LINK 2] [LINK 2] -->
  
	<link name="link_${finger_num*4+2}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link2_t_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link2_t_z/2}"/>
      <material name="black">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+2}" type="revolute">
    <axis xyz="0 1 0"/>
     <limit effort="0" velocity="0" lower="${limit_2_t_low+joint_safety_margin}" upper="${limit_2_t_up-joint_safety_margin}" />
    <parent link="link_${finger_num*4+1}"/>
    <child link="link_${finger_num*4+2}"/>
    <origin xyz="0 0 ${link1_t_z}"/>
  </joint>  
  
 
<!-- [LINK 3] [LINK 3] [LINK 3] [LINK 3]  [LINK 3] [LINK 3] [LINK 3] -->
  
	<link name="link_${finger_num*4+3}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link3_t_z-fingerTip_r}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${(link3_t_z-fingerTip_r)/2}"/>
      <material name="blue">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+3}" type="revolute">
    <axis xyz="0 1 0"/>
     <limit effort="0" velocity="0" lower="${limit_3_t_low+joint_safety_margin}" upper="${limit_3_t_up-joint_safety_margin}" />
    <parent link="link_${finger_num*4+2}"/>
    <child link="link_${finger_num*4+3}"/>
    <origin xyz="0 0 ${link2_t_z}"/>
  </joint>      
    
<!-- [FINGER TIP] -->
  
	<link name="link_${finger_num*4+3}_tip">	
    <visual>
      <geometry>
        <sphere radius="${fingerTip_r}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link3_t_z-fingerTip_r}"/>
      <material name="white">
        <color rgba=".9 .9 .9 1"/>
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+3}_tip" type="fixed">
    <parent link="link_${finger_num*4+3}"/>
    <child link="link_${finger_num*4+3}_tip"/>
    <origin xyz="0 0 0"/>
  </joint>   
  
</xacro:macro>
<!-- [[END]] THUMB MACRO -->































<!-- THREE FINGER MACRO -->
<xacro:macro name="finger" params="finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r">


<!-- [LINK 0] [LINK 0] [LINK 0] [LINK 0]  [LINK 0] [LINK 0] [LINK 0] -->
  
	<link name="link_${finger_num*4+0}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link0_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link0_z/2}"/>
      <material name="black">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+0}" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="${limit_0_low+joint_safety_margin}" upper="${limit_0_up-joint_safety_margin}" />
    <parent link="base_link"/>
    <child link="link_${finger_num*4+0}"/>
    <origin rpy="${finger_angle_r} 0 0" xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
  </joint>
  
  
<!-- [LINK 1] [LINK 1] [LINK 1] [LINK 1]  [LINK 1] [LINK 1] [LINK 1] -->
  
	<link name="link_${finger_num*4+1}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link1_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link1_z/2}"/>
      <material name="blue">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+1}" type="revolute">
  <limit effort="0" velocity="0" lower="${limit_1_low+joint_safety_margin}" upper="${limit_1_up-joint_safety_margin}" />
    <axis xyz="0 1 0"/>
    <parent link="link_${finger_num*4+0}"/>
    <child link="link_${finger_num*4+1}"/>
    <origin xyz="0 0 ${link0_z}"/>
  </joint>  


<!-- [LINK 2] [LINK 2] [LINK 2] [LINK 2]  [LINK 2] [LINK 2] [LINK 2] -->
  
	<link name="link_${finger_num*4+2}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link2_z}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link2_z/2}"/>
      <material name="black">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+2}" type="revolute">
  
    <axis xyz="0 1 0"/>
    <limit effort="0" velocity="0" lower="${limit_2_low+joint_safety_margin}" upper="${limit_2_up-joint_safety_margin}" />
    <parent link="link_${finger_num*4+1}"/>
    <child link="link_${finger_num*4+2}"/>
    <origin xyz="0 0 ${link1_z}"/>
  </joint>  
  
 
<!-- [LINK 3] [LINK 3] [LINK 3] [LINK 3]  [LINK 3] [LINK 3] [LINK 3] -->
  
	<link name="link_${finger_num*4+3}">	
    <visual>
      <geometry>
        <box size="${links_x} ${links_y} ${link3_z-fingerTip_r}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${(link3_z-fingerTip_r)/2}"/>
      <material name="blue">
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+3}" type="revolute">
    <axis xyz="0 1 0"/>
    <limit effort="0" velocity="0" lower="${limit_3_low+joint_safety_margin}" upper="${limit_3_up-joint_safety_margin}" />
    <parent link="link_${finger_num*4+2}"/>
    <child link="link_${finger_num*4+3}"/>
    <origin xyz="0 0 ${link2_z}"/>
  </joint>      
    
<!-- [FINGER TIP] -->
  
	<link name="link_${finger_num*4+3}_tip">	
    <visual>
      <geometry>
        <sphere radius="${fingerTip_r}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${link3_z-fingerTip_r}"/>
      <material name="white">
        <color rgba=".9 .9 .9 1"/>
      </material>
    </visual>   
  </link>
  
  <joint name="joint_${finger_num*4+3}_tip" type="fixed">
    <parent link="link_${finger_num*4+3}"/>
    <child link="link_${finger_num*4+3}_tip"/>
    <origin xyz="0 0 0"/>
  </joint>   
  
</xacro:macro>
<!-- [[END]] THREE FINGER MACRO -->
    
</robot>

